### PR TITLE
Show groupmanager status in ajax members list and group persons template

### PR DESCRIPTION
**Pull request by gagnieray**
We missed the ajax template... :sweat_smile:

### CODE REVIEW

**Comment by gagnieray** [comment]
> We missed the ajax template... 😅

And an other one ! :rofl:

I searched for `isStaff()` through all the templates and I think this time it's OK !

**Comment by gagnieray** [comment]
> [...] I think this time it's OK !

No... There is still something wrong... :disappointed:

**Review by trasher — APPROVED** [review]

**Comment by trasher** [comment]
Good catch, thanks! :)

**Comment by gagnieray** [comment]
> Good catch, thanks! :)

However, this time again, `isStaff()` always returns false. Even for groupmanagers 😞

https://github.com/galette/galette/blob/3db69f0f35c6202489c27dc1faabade467f412ba/galette/templates/default/elements/group_persons.html.twig#L44-L48

**Comment by trasher** [comment]
On my local instance, all seems correct:
image

In the above image, we can see admins, staff members and group managers icons while selecting groups members from the modal.

**Comment by gagnieray** [comment]
This time I am not talking about the list in the modal, but the list in the group's members tab which is loaded differently and misses `priorite_statut`.

Capture d’écran de 2023-09-29 09-14-00

https://github.com/galette/galette/blob/3db69f0f35c6202489c27dc1faabade467f412ba/galette/lib/Galette/Repository/Groups.php#L459-L493

**Comment by trasher** [comment]
> This time I am not talking about the list in the modal, but the list in the group's members tab which is loaded differently and misses `priorite_statut`.
> 
> Capture d’écran de 2023-09-29 09-14-00
> 
> https://github.com/galette/galette/blob/3db69f0f35c6202489c27dc1faabade467f412ba/galette/lib/Galette/Repository/Groups.php#L459-L493

Oh, OK! I'll fix

**Comment by trasher** [comment]
`Repository\Groups::getManagerUsers()` is no (longer?) used in core but in Auto plugin. Faulty method here was `Entity\Groups::loadPersons()`; both have been fixed, see a4b4d867500a2c01aff2d649dd08b823872ada73

**Comment by gagnieray** [comment]
Thanks!

**Pull request merged**
