### PR TITLE
Fix reminders unit tests; refs #1614

### PR DESCRIPTION
**Pull request by gagnieray**

### CODE REVIEW

**Comment by trasher** [comment]
Thank you very much, I'll take a look

**Comment by gagnieray** [comment]
> My latest commit fixes tests; could you confirm it seems working as expected on your side @gagnieray?

Unfortunately, no :confused:

I wrote more tests. But they do not fail as expected (or at least not in the same conditions as things are failing on my instance). So I wonder if I wrote them correctly :thinking: 

Please, have a look at my latest commit.
And compare the results of the latest tests on github with my own below :

1. On case n°1 : https://github.com/galette/galette/blob/9ea3ecde3e04086c0b34634b91d06360ad097a26/tests/Galette/Repository/tests/units/Reminders.php#L663-L665
    - first impending reminders are properly sent
    - second impending reminders fail
    - first late reminders fail
    - second late reminders are properly sent

2. On case n°2 : https://github.com/galette/galette/blob/9ea3ecde3e04086c0b34634b91d06360ad097a26/tests/Galette/Repository/tests/units/Reminders.php#L904-L910
    - first impending reminders are properly sent
    - second impending reminders fail
    - first late reminders fail : only one out of two reminders is sent for the member late for more than 1 year
    - second late reminders are properly sent

3. On case n°3 : https://github.com/galette/galette/blob/9ea3ecde3e04086c0b34634b91d06360ad097a26/tests/Galette/Repository/tests/units/Reminders.php#L1136-L1140
    - first impending reminder is properly sent
    - second impending reminder fails
    - first late reminder fails
    - second late reminder is properly sent

**Comment by trasher** [comment]
> > My latest commit fixes tests; could you confirm it seems working as expected on your side @gagnieray?
> 
> Unfortunately, no 😕
> 
> I wrote more tests. But they do not fail as expected (or at least not in the same conditions as things are failing on my instance). So I wonder if I wrote them correctly 🤔
> [...]

After a quick review, I did no see anything wrong in your tests; but I probably need to spend much more time on that.

I've released 1.0.0 final, reminder issue is very old; I'll release a bugfixes version once it will be fixed.

I'll take a closer look later, thanks for the tests updates; maybe will I finally understand what's wrong :/

**Comment by trasher** [comment]
I've tried to understand why your latest commit make tests fails; but the only conclusion I got is tests expectations are currently wrong :D
But I also must admit I'm a bit lost in this test case... I'll probably revert your latest change to and work on a brand new test case reproducing what you describe on the tracker ticket.

Xmas approaching, I'm not sure I can take an eye before next year :)

**Comment by trasher** [comment]
1st and 2nd commits have been merged in #373; third commit has been ignored as I said, and last one is already in develop branch :)

**Pull request closed without merging**
